// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWq9LbVavf0gVVQDxo0atJ3PWdcxQvVIY',
    appId: '1:324347420171:web:f4e20321a9dfe6097bf10e',
    messagingSenderId: '324347420171',
    projectId: 'thanutdata2026',
    authDomain: 'thanutdata2026.firebaseapp.com',
    storageBucket: 'thanutdata2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQqv7MNLz6AqxNZcBHOv-AAsqFPDfnzU',
    appId: '1:324347420171:android:a03a382823e839ce7bf10e',
    messagingSenderId: '324347420171',
    projectId: 'thanutdata2026',
    storageBucket: 'thanutdata2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJ4gJjx_T8BMWEvW4W3TwfYL_w4YBVlI',
    appId: '1:324347420171:ios:f638c82861df71417bf10e',
    messagingSenderId: '324347420171',
    projectId: 'thanutdata2026',
    storageBucket: 'thanutdata2026.firebasestorage.app',
    iosBundleId: 'com.example.cw13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJ4gJjx_T8BMWEvW4W3TwfYL_w4YBVlI',
    appId: '1:324347420171:ios:f638c82861df71417bf10e',
    messagingSenderId: '324347420171',
    projectId: 'thanutdata2026',
    storageBucket: 'thanutdata2026.firebasestorage.app',
    iosBundleId: 'com.example.cw13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWq9LbVavf0gVVQDxo0atJ3PWdcxQvVIY',
    appId: '1:324347420171:web:564134b5bf2fe0d67bf10e',
    messagingSenderId: '324347420171',
    projectId: 'thanutdata2026',
    authDomain: 'thanutdata2026.firebaseapp.com',
    storageBucket: 'thanutdata2026.firebasestorage.app',
  );
}
